# Generated by Django 5.2.4 on 2025-07-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='topic',
            field=models.CharField(default='University', max_length=255),
            preserve_default=False,
        ),
    ]
